# Generated by Django 3.1.7 on 2021-05-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('price', models.FloatField()),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('motor_power', models.IntegerField()),
                ('engine_capacity', models.IntegerField()),
                ('case_type', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('TRUE', 'EVET'), ('FALSE', 'HAYIR')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
