# Generated by Django 3.1.7 on 2021-05-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210527_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='menu',
        ),
    ]
