# Generated by Django 3.1.7 on 2021-05-27 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_content_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.menu'),
        ),
    ]
